import {
  Book,
  Briefcase,
  Globe,
  GraduationCap,
  LucideIcon,
  Music,
  Palette,
  Trophy,
  Utensils,
} from "lucide-react";
import { Event } from "../../components/types";

export const eventIcons: Record<string, LucideIcon> = {
  Cultural: Globe,
  Career: Briefcase,
  Academic: GraduationCap,
  Food: Utensils,
  Music: Music,
  Workshop: Book,
  Art: Palette,
  Sports: Trophy,
  default: Globe,
};

export const categories = [
  "All",
  "Cultural",
  "Career",
  "Academic",
  "Birthday",
  "Sports",
  "Art",
];
export const eventTypes = [
  "All",
  "Upcoming",
  "Past",
  "Key",
  "Mandatory",
  "Birthday",
];
export const organizers = [
  "All",
  "ISA",
  "AAMU Athletics",
  "AAMU Career Services",
  "AAMU Departments",
];
export const tags = [
  "cultural",
  "food",
  "social",
  "career",
  "academic",
  "workshop",
  "sports",
  "art",
];

export const aamuColors = {
  primary: "#660000", // AAMU Maroon
  secondary: "#FFD700", // AAMU Gold
  tertiary: "#FFFFFF", // White
  background: "#F5F5F5", // Light gray background
};

export const eventColors: Record<string, string> = {
  Cultural: "#FF6B6B", // Coral
  Career: "#4ECDC4", // Teal
  Academic: "#45B7D1", // Sky Blue
  Birthday: "#FF8ED4", // Pink
  Sports: "#59D4E8", // Light Blue
  Art: "#FFA07A", // Light Salmon
  default: "#A0A0A0", // Gray for other categories
};

export const events: Event[] = [
  {
    id: 1,
    title: "International Food Festival",
    date: new Date(2023, 8, 15),
    time: "12:00 PM - 4:00 PM",
    description:
      "Experience cuisines from around the world prepared by our international students.",
    location: "AAMU Quad",
    attendees: 120,
    organizer: "ISA",
    tags: ["cultural", "food", "social"],
    category: "Cultural",
    isKeyEvent: true,
    isMandatory: false,
    icon: "Food",
    dresscode: "Casual",
    foodServed: true,
  },
  {
    id: 2,
    title: "Career Networking Fair",
    date: new Date(2023, 9, 20),
    time: "10:00 AM - 2:00 PM",
    description: "Meet recruiters and professionals for career networking.",
    location: "Student Center",
    attendees: 200,
    organizer: "Career Services",
    tags: ["career", "networking"],
    category: "Professional",
    isKeyEvent: true,
    isMandatory: true,
    icon: "Briefcase",
    dresscode: "Business Casual",
    foodServed: false,
  },
  {
    id: 3,
    title: "ISA Welcome Night",
    date: new Date(2023, 8, 25),
    time: "6:00 PM - 9:00 PM",
    description: "A fun-filled night to welcome new international students.",
    location: "Student Lounge",
    attendees: 150,
    organizer: "ISA",
    tags: ["social", "fun"],
    category: "Social",
    isKeyEvent: true,
    isMandatory: false,
    icon: "Welcome",
    dresscode: "Casual",
    foodServed: true,
  },
  {
    id: 4,
    title: "Cultural Dance Workshop",
    date: new Date(2023, 10, 10),
    time: "2:00 PM - 4:00 PM",
    description: "Learn traditional dances from around the world.",
    location: "Gymnasium",
    attendees: 75,
    organizer: "ISA",
    tags: ["cultural", "dance", "workshop"],
    category: "Cultural",
    isKeyEvent: false,
    isMandatory: false,
    icon: "Dance",
    dresscode: "Sportswear",
    foodServed: false,
  },
  {
    id: 5,
    title: "Midterm Study Jam",
    date: new Date(2023, 9, 30),
    time: "5:00 PM - 11:00 PM",
    description: "Join other students for a focused study session.",
    location: "Library",
    attendees: 50,
    organizer: "Academic Support",
    tags: ["study", "academic"],
    category: "Academic",
    isKeyEvent: false,
    isMandatory: true,
    icon: "Book",
    dresscode: "Comfortable",
    foodServed: true,
  },
  {
    id: 6,
    title: "Community Service Day",
    date: new Date(2023, 10, 5),
    time: "8:00 AM - 2:00 PM",
    description: "Help clean up and improve local parks.",
    location: "Huntsville Parks",
    attendees: 80,
    organizer: "ISA",
    tags: ["service", "community"],
    category: "Volunteer",
    isKeyEvent: false,
    isMandatory: true,
    icon: "Leaf",
    dresscode: "Work Clothes",
    foodServed: false,
  },
  {
    id: 7,
    title: "International Film Night",
    date: new Date(2023, 10, 12),
    time: "7:00 PM - 10:00 PM",
    description: "Watch films from different countries with English subtitles.",
    location: "Student Center Theater",
    attendees: 60,
    organizer: "ISA",
    tags: ["film", "cultural", "entertainment"],
    category: "Cultural",
    isKeyEvent: false,
    isMandatory: false,
    icon: "Film",
    dresscode: "Casual",
    foodServed: true,
  },
  {
    id: 8,
    title: "Sports Day",
    date: new Date(2023, 9, 18),
    time: "9:00 AM - 3:00 PM",
    description:
      "Participate in soccer, basketball, and volleyball tournaments.",
    location: "Campus Sports Grounds",
    attendees: 100,
    organizer: "ISA",
    tags: ["sports", "physical activity"],
    category: "Sports",
    isKeyEvent: true,
    isMandatory: false,
    icon: "Ball",
    dresscode: "Sportswear",
    foodServed: true,
  },
  {
    id: 9,
    title: "International Alumni Panel",
    date: new Date(2023, 11, 1),
    time: "3:00 PM - 5:00 PM",
    description: "Hear from international alumni about their career journeys.",
    location: "Lecture Hall 101",
    attendees: 90,
    organizer: "ISA",
    tags: ["career", "alumni", "panel"],
    category: "Professional",
    isKeyEvent: false,
    isMandatory: true,
    icon: "Mic",
    dresscode: "Business Casual",
    foodServed: false,
  },
  {
    id: 10,
    title: "Thanksgiving Potluck",
    date: new Date(2023, 11, 24),
    time: "1:00 PM - 5:00 PM",
    description: "Join us for a potluck Thanksgiving feast.",
    location: "AAMU Quad",
    attendees: 130,
    organizer: "ISA",
    tags: ["holiday", "food", "social"],
    category: "Social",
    isKeyEvent: false,
    isMandatory: false,
    icon: "Turkey",
    dresscode: "Casual",
    foodServed: true,
  },
  {
    id: 11,
    title: "Winter Formal Gala",
    date: new Date(2023, 12, 8),
    time: "7:00 PM - 11:00 PM",
    description: "Dress up and enjoy an evening of dancing and entertainment.",
    location: "Ballroom",
    attendees: 200,
    organizer: "ISA",
    tags: ["formal", "gala", "social"],
    category: "Social",
    isKeyEvent: true,
    isMandatory: false,
    icon: "Star",
    dresscode: "Formal",
    foodServed: true,
  },
  {
    id: 12,
    title: "Spring Break Trip",
    date: new Date(2024, 3, 15),
    time: "8:00 AM - 6:00 PM",
    description: "Join us for a day trip to the beach during spring break.",
    location: "Gulf Shores Beach",
    attendees: 80,
    organizer: "ISA",
    tags: ["travel", "spring break"],
    category: "Recreational",
    isKeyEvent: false,
    isMandatory: false,
    icon: "Sun",
    dresscode: "Beachwear",
    foodServed: true,
  },
  // Add more events here...
];
